name: Hola

on:
  push:
    branches:
      - master

jobs:
  hello_word:
    runs-on: ubuntu-20.04
    steps:
      - name: Echo the message
        run: |
          echo "Ejecuntado Accion!"
      - name: Dime la fecha
        run: |
          Date
      - run: ls -l
      