name: Deployment Pipeline

on:
  push:
    branches:
      - master
  
jobs:
  deploy:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 14
      - name: Instalar dependencias
        run: npm i